# Generated by Django 5.0.6 on 2024-05-13 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.app_user')),
            ],
        ),
        migrations.DeleteModel(
            name='Password',
        ),
    ]
